services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    ports:
      - "4001:3306"
    volumes:
      - ./mysql:/var/lib/mysql
