"""alterando as datas

Revision ID: bf474caa17de
Revises: 83fff9ea69fd
Create Date: 2025-01-22 20:08:36.828215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bf474caa17de'
down_revision: Union[str, None] = '83fff9ea69fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comanda', 'data_hora_abertura',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('comanda', 'data_hora_fechamento',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comanda', 'data_hora_fechamento',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('comanda', 'data_hora_abertura',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
