"""2

Revision ID: 93dcb59acd08
Revises: b9de0d8ffc03
Create Date: 2025-01-16 10:51:50.862423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '93dcb59acd08'
down_revision: Union[str, None] = 'b9de0d8ffc03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('numero_mesa', table_name='mesa')
    op.drop_table('mesa')
    op.drop_table('ingrediente')
    op.drop_table('cliente')
    op.drop_table('prato')
    op.drop_index('id_mesa', table_name='comanda')
    op.drop_table('comanda')
    op.drop_table('comandapratolink')
    op.drop_table('pratoingredientelink')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pratoingredientelink',
    sa.Column('id_prato', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_ingrediente', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade_utilizada', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['id_ingrediente'], ['ingrediente.id'], name='pratoingredientelink_ibfk_2'),
    sa.ForeignKeyConstraint(['id_prato'], ['prato.id'], name='pratoingredientelink_ibfk_1'),
    sa.PrimaryKeyConstraint('id_prato', 'id_ingrediente'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('comandapratolink',
    sa.Column('id_comanda', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_prato', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_comanda'], ['comanda.id'], name='comandapratolink_ibfk_1'),
    sa.ForeignKeyConstraint(['id_prato'], ['prato.id'], name='comandapratolink_ibfk_2'),
    sa.PrimaryKeyConstraint('id_comanda', 'id_prato'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('comanda',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_mesa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_hora_abertura', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('data_hora_fechamento', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], name='comanda_ibfk_1'),
    sa.ForeignKeyConstraint(['id_mesa'], ['mesa.id'], name='comanda_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id_mesa', 'comanda', ['id_mesa'], unique=True)
    op.create_table('prato',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('preco', mysql.FLOAT(), nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('disponivel', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cliente',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cpf', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ingrediente',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('estoque', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('quantidade_estoque', mysql.FLOAT(), nullable=False),
    sa.Column('peso', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mesa',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero_mesa', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('capacidade', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ocupada', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('numero_pessoas', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('numero_mesa', 'mesa', ['numero_mesa'], unique=True)
    # ### end Alembic commands ###
